# Generated by Django 4.1.7 on 2024-05-31 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
