# Generated by Django 4.1.7 on 2024-05-30 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalitem',
            name='daily_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rentalitem',
            name='market_value',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rentalitem',
            name='monthly_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rentalitem',
            name='weekly_price',
            field=models.IntegerField(),
        ),
    ]
