# Generated by Django 5.0.6 on 2024-06-03 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_remove_rentalitem_category_rentalitem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalitem',
            name='Category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Category', to='items.category'),
        ),
    ]
