# Generated by Django 5.0.6 on 2024-06-03 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_itemcategory_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentalitem',
            old_name='Category',
            new_name='Category_of_items',
        ),
    ]
