# Generated by Django 5.0.6 on 2024-06-04 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_checkoutinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutinfo',
            name='Category_of_items_checkout',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Category_item_checkout', to='items.itemcategory'),
        ),
        migrations.AddField(
            model_name='checkoutinfo',
            name='rental_items_checkout',
            field=models.ManyToManyField(related_name='checkouts', to='items.rentalitem'),
        ),
    ]
