# Generated by Django 5.0.6 on 2024-06-04 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0011_checkoutinfo_category_of_items_checkout_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoutinfo',
            name='rental_items_checkout',
        ),
        migrations.AddField(
            model_name='checkoutinfo',
            name='rental_item_checkout',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checkout', to='items.rentalitem'),
        ),
    ]
